_target_: fakeglyph.model.generator.Generator
input_shape:
  - 16
  - 1
  - 1
layers:
  _target_: torch.nn.Sequential
  _args_:
    # 1
    - _target_: fakeglyph.model.units.ConvTransposeBNReLU2d
      in_channels: 16
      out_channels: 128
      kernel_size: 8
      bias: false
    # 8
    - _target_: fakeglyph.model.units.ConvTransposeBNReLU2d.upsample
      in_channels: 128
    # 16
    - _target_: fakeglyph.model.units.ConvTransposeBNReLU2d.upsample
      in_channels: 64
    # 32
    - _target_: torch.nn.ConvTranspose2d
      in_channels: 32
      out_channels: 1
      kernel_size: 4
      stride: 2
      padding: 1
    # 64
    - _target_: torch.nn.Sigmoid
