_target_: torch.nn.Sequential
_args_:
  # 64
  - _target_: fakeglyph.model.units.ConvBNReLU2d
    in_channels: 1
    out_channels: 8
    kernel_size: 8
    stride: 4
    padding: 2
    bias: false
  # 16
  - _target_: fakeglyph.model.units.ConvBNReLU2d.downsample
    in_channels: 8
  # 8
  - _target_: fakeglyph.model.units.ConvBNReLU2d.downsample
    in_channels: 16
  # 4
  - _target_: torch.nn.Conv2d
    in_channels: 32
    out_channels: 1
    kernel_size: 4
  # 1
