_target_: torch.nn.Sequential
_args_:
  # 64
  - _target_: fakeglyph.model.units.ConvBNReLU2d
    in_channels: 1
    out_channels: 32
    kernel_size: 4
    stride: 2
    padding: 1
    bias: false
  # 32
  - _target_: fakeglyph.model.units.ResBlockInterpolate2d.downsample
    in_channels: 32
  # 16
  - _target_: fakeglyph.model.units.ResBlockInterpolate2d.downsample
    in_channels: 64
  # 8
  - _target_: fakeglyph.model.units.ResBlockInterpolate2d.downsample
    in_channels: 128
  # 4
  - _target_: torch.nn.Conv2d
    in_channels: 256
    out_channels: 256
    kernel_size: 4
  # 1
